InstaCart

In [1]:
import numpy as np
import pandas as pd
import altair as alt

In [2]:
aisles = pd.read_csv('aisles.csv')
departments = pd.read_csv('departments.csv')
order_products_prior = pd.read_csv('order_products__prior.csv')
order_products_train = pd.read_csv('order_products__train.csv')
orders = pd.read_csv('orders.csv')
products = pd.read_csv('products.csv')

In [3]:
# Exploring data sets

In [4]:
aisles.head()

   aisle_id                       aisle
0         1       prepared soups salads
1         2           specialty cheeses
2         3         energy granola bars
3         4               instant foods
4         5  marinades meat preparation

In [5]:
departments.head()

   department_id department
0              1     frozen
1              2      other
2              3     bakery
3              4    produce
4              5    alcohol

In [6]:
orders.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [7]:
products.head()

,product_id,product_name,aisle_id,department_id
0,1,Chocolate Sandwich Cookies,61,19
1,2,All-Seasons Salt,104,13
2,3,Robust Golden Unsweetened Oolong Tea,94,7
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1
4,5,Green Chile Anytime Sauce,5,13

In [8]:
order_products_prior.head()

   order_id  product_id  add_to_cart_order  reordered
0         2       33120                  1          1
1         2       28985                  2          1
2         2        9327                  3          0
3         2       45918                  4          1
4         2       30035                  5          0

In [9]:
order_products_train.head()

   order_id  product_id  add_to_cart_order  reordered
0         1       49302                  1          1
1         1       11109                  2          1
2         1       10246                  3          0
3         1       49683                  4          0
4         1       43633                  5          1

In [10]:
# Concating order prior and train

In [11]:
order_products = pd.concat([order_products_prior,order_products_train])
order_products.shape

(33819106, 4)

In [12]:
# Creating test, trian, prior set

In [13]:
test = orders[orders['eval_set'] == 'test']
test.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
38,2774568,3,test,13,5,15,11.0
44,329954,4,test,6,3,12,30.0
53,1528013,6,test,4,3,16,22.0
96,1376945,11,test,8,6,11,8.0
102,1356845,12,test,6,1,20,30.0

In [14]:
train = orders[orders['eval_set'] == 'train']
train.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
10,1187899,1,train,11,4,8,14.0
25,1492625,2,train,15,1,11,30.0
49,2196797,5,train,5,0,11,6.0
74,525192,7,train,21,2,11,6.0
78,880375,8,train,4,1,14,10.0

In [15]:
prior = orders[orders['eval_set'] == 'prior']
prior.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [16]:
# Creating final data set

In [17]:
data = pd.merge(orders, order_products, on='order_id')

In [18]:
data.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered
0,2539329,1,prior,1,2,8,NaN,196,1,0
1,2539329,1,prior,1,2,8,NaN,14084,2,0
2,2539329,1,prior,1,2,8,NaN,12427,3,0
3,2539329,1,prior,1,2,8,NaN,26088,4,0
4,2539329,1,prior,1,2,8,NaN,26405,5,0

In [19]:
data = pd.merge(data, products, on='product_id')
data.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id
0,2539329,1,prior,1,2,8,NaN,196,1,0,Soda,77,7
1,2398795,1,prior,2,3,7,15.0,196,1,1,Soda,77,7
2,473747,1,prior,3,3,12,21.0,196,1,1,Soda,77,7
3,2254736,1,prior,4,4,7,29.0,196,1,1,Soda,77,7
4,431534,1,prior,5,4,15,28.0,196,1,1,Soda,77,7

In [20]:
data = pd.merge(data, aisles, on='aisle_id')
data = pd.merge(data, departments, on='department_id')
data.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,aisle,department
0,2539329,1,prior,1,2,8,NaN,196,1,0,Soda,77,7,soft drinks,beverages
1,2398795,1,prior,2,3,7,15.0,196,1,1,Soda,77,7,soft drinks,beverages
2,473747,1,prior,3,3,12,21.0,196,1,1,Soda,77,7,soft drinks,beverages
3,2254736,1,prior,4,4,7,29.0,196,1,1,Soda,77,7,soft drinks,beverages
4,431534,1,prior,5,4,15,28.0,196,1,1,Soda,77,7,soft drinks,beverages

In [21]:
# Explanatory data analysis

In [22]:
from altair import pipe, limit_rows, to_values
t = lambda data: pipe(data, limit_rows(max_rows=1000000000), to_values)
alt.data_transformers.register('custom', t)
alt.data_transformers.enable('custom')

DataTransformerRegistry.enable('custom')

In [23]:
#How many orders, items, and users are in each eval set?

In [24]:
count = pd.DataFrame(orders.groupby('eval_set')['order_number'].count()) 
count['i'] = count.index
count

          order_number      i
eval_set
prior          3214874  prior
test             75000   test
train           131209  train

In [25]:
n = alt.Chart(count, height = 350, width = 450,title = 'Orders as per Evaluation Set').mark_bar().encode(
    x='i',
    y='order_number',
    color = alt.Color('i', legend=None)
).configure_axis(
    labelFontSize=16,
    titleFontSize=16,
    grid = False
).configure_title(fontSize=24)


n.encoding.y.title = 'Number of Orders'
n.encoding.x.title = 'Evalution set'

n

alt.Chart(...)

In [26]:
count = pd.DataFrame(data.groupby('eval_set')['order_number'].count()) 
count['i'] = count.index
count

          order_number      i
eval_set
prior         32434489  prior
train          1384617  train

In [27]:
n = alt.Chart(count, height = 350, width = 450,title = 'Orders as per Evaluation Set').mark_bar().encode(
    x='i',
    y='order_number',
    color = alt.Color('i', legend=None)
).configure_axis(
    labelFontSize=16,
    titleFontSize=16,
    grid = False
).configure_title(fontSize=24)


n.encoding.y.title = 'Number of Orders'
n.encoding.x.title = 'Evalution set'

n

alt.Chart(...)

In [28]:
count = pd.DataFrame(orders.groupby('eval_set')['user_id'].nunique())
count['i'] = count.index
count

          user_id      i
eval_set
prior      206209  prior
test        75000   test
train      131209  train

In [29]:
n = alt.Chart(count, height = 350, width = 450,title = 'Number of Users').mark_bar().encode(
    x='i',
    y='user_id',
    color = alt.Color('i', legend=None)
).configure_axis(
    labelFontSize=16,
    titleFontSize=16,
    grid = False
).configure_title(fontSize=24)


n.encoding.y.title = 'Users'
n.encoding.x.title = 'Evalution set'

n

alt.Chart(...)

In [30]:
#How many users in prior appear in train? How many users in prior or train appear in test?

In [31]:
len(pd.Series(list(set(prior['user_id']) & set(test['user_id']))))

75000

In [32]:
len(pd.Series(list(set(prior['user_id']) & set(train['user_id']))))

131209

In [33]:
len(pd.Series(list(set(train['user_id']) & set(test['user_id']))))

0

In [34]:
#When are orders made?

In [35]:
count = pd.DataFrame(orders.groupby('order_dow')['order_number'].count()) 
count['i'] = count.index + 1
count

           order_number  i
order_dow
0                600905  1
1                587478  2
2                467260  3
3                436972  4
4                426339  5
5                453368  6
6                448761  7

In [36]:
n = alt.Chart(count, height = 350, width = 350,title = 'Number of Orders on Each day of Week').mark_bar(size=25).encode(
    x='i',
    y='order_number'
).configure_axis(
    labelFontSize=16,
    titleFontSize=16,
    grid = False
).configure_title(fontSize=24)


n.encoding.y.title = 'Number of order'
n.encoding.x.title = 'Day of the Week'

n

alt.Chart(...)

In [37]:
count = pd.DataFrame(orders.groupby('order_hour_of_day')['order_number'].count()) 
count['i'] = count.index + 1
count.head()

                   order_number  i
order_hour_of_day
0                         22758  1
1                         12398  2
2                          7539  3
3                          5474  4
4                          5527  5

In [38]:
n = alt.Chart(count, height = 350, width = 750,title = 'Number of Orders on Each day of Week').mark_bar(size=20).encode(
    x='i',
    y='order_number'
).configure_axis(
    labelFontSize=16,
    titleFontSize=16,
    grid = False
).configure_title(fontSize=24)


n.encoding.y.title = 'Number of order'
n.encoding.x.title = 'Day of the Week'

n

alt.Chart(...)

In [39]:
count = pd.DataFrame(orders.groupby('days_since_prior_order')['order_number'].count()) 
count['i'] = count.index + 1
count.head()

                        order_number    i
days_since_prior_order
0.0                            67755  1.0
1.0                           145247  2.0
2.0                           193206  3.0
3.0                           217005  4.0
4.0                           221696  5.0

In [40]:
alt.Chart(count, width = 750, height = 350).mark_bar(size = 20).encode(
    alt.X("i", title = 'Date'),
    alt.Y("order_number", title='Number of Order')
).configure_axis(
    labelFontSize=16,
    titleFontSize=16,
    grid = False
).configure_title(fontSize = 24)

alt.Chart(...)

In [41]:
hourDow = orders.groupby(['order_dow', 'order_hour_of_day'])['order_number'].aggregate('count').reset_index()
hourDow

     order_dow  order_hour_of_day  order_number
0            0                  0          3936
1            0                  1          2398
2            0                  2          1409
3            0                  3           963
4            0                  4           813
..         ...                ...           ...
163          6                 19         18346
164          6                 20         13392
165          6                 21         10501
166          6                 22          8532
167          6                 23          6087

[168 rows x 3 columns]

In [42]:
alt.Chart(hourDow, title='No of order day of week vs hour of day').mark_rect().encode(
    x = alt.X('order_hour_of_day:O', title='Hour of the Day'),
    y = alt.Y('order_dow:O', title='Day of Week'),
    color = 'order_number:Q'
).configure_axis(
    labelFontSize=16,
    titleFontSize=16
).configure_title(
    fontSize = 24
).properties(
    height = 450,
    width = 450
)

alt.Chart(...)

In [43]:
#Count of Users by Number of Prior Orders

In [44]:
count = pd.DataFrame(orders.groupby('user_id')['order_number'].aggregate('max').reset_index()) 
count

        user_id  order_number
0             1            11
1             2            15
2             3            13
3             4             6
4             5             5
...         ...           ...
206204   206205             4
206205   206206            68
206206   206207            17
206207   206208            50
206208   206209            14

[206209 rows x 2 columns]

In [45]:
new = pd.DataFrame(count['order_number'].value_counts())
new['i'] = new.index
new.head()

   order_number  i
4         23986  4
5         19590  5
6         16165  6
7         13850  7
8         11700  8

In [46]:
alt.Chart(new, title='Count of users by number of prior orders').mark_bar().encode(
    alt.X('i', title = 'Number of Prior Orders'),
    alt.Y('order_number', title = 'Number of Users')
).configure_axis(
    labelFontSize = 16,
    titleFontSize = 16,
    grid = False
).configure_title(
    fontSize = 24
).properties(
    height = 400,
    width = 700
).configure_bar(
    color = '#7AAD80'
)

alt.Chart(...)

In [47]:
# Distribution of basket size

In [48]:
OrderSize = data.reset_index().groupby(['user_id', 'order_number'])['add_to_cart_order'].aggregate('max')
new = pd.DataFrame(OrderSize.value_counts())
new['i'] = new.index
new

     add_to_cart_order    i
5               237225    5
6               236383    6
4               230299    4
7               228547    7
3               215060    3
..                 ...  ...
112                  1  112
105                  1  105
94                   1   94
90                   1   90
145                  1  145

[113 rows x 2 columns]

In [49]:
alt.Chart(new, title='Count of users by number of Items in Basket').mark_bar(size = 4).encode(
    alt.X('i', title = 'Number of Items in Basket'),
    alt.Y('add_to_cart_order', title = 'Number of Users')
).configure_axis(
    labelFontSize = 16,
    titleFontSize = 16,
    grid = False
).configure_title(
    fontSize = 24
).properties(
    height = 350,
    width = 750
).configure_bar(
    color = '#FC5959'
)

alt.Chart(...)

In [50]:
# Popular Products

In [51]:
countProducts = pd.crosstab(data.product_name, data.eval_set)
countProducts['total'] = countProducts.prior + countProducts.train
count = countProducts.sort_values(by='total', ascending=False).head(25)
count['i'] = count.index
count.head(10)

eval_set                 prior  train   total                       i
product_name
Banana                  472565  18726  491291                  Banana
Bag of Organic Bananas  379450  15480  394930  Bag of Organic Bananas
Organic Strawberries    264683  10894  275577    Organic Strawberries
Organic Baby Spinach    241921   9784  251705    Organic Baby Spinach
Organic Hass Avocado    213584   7293  220877    Organic Hass Avocado
Organic Avocado         176815   7409  184224         Organic Avocado
Large Lemon             152657   8135  160792             Large Lemon
Strawberries            142951   6494  149445            Strawberries
Limes                   140627   6033  146660                   Limes
Organic Whole Milk      137905   4908  142813      Organic Whole Milk

In [52]:
m = alt.Chart(count, title="Count of Order of prior 25 Most Ordered Product").mark_bar(size = 7).encode(
    alt.X('i', title = 'Product Name'),
    alt.Y('prior', title = 'Count of Orders')
).properties(
    height = 350,
    width = 350
)
n = alt.Chart(count, title="Count of Order of train 25 Most Ordered Product").mark_bar(size = 7).encode(
    alt.X('i', title = 'Product Name'),
    alt.Y('train', title = 'Count of Orders')
).properties(
    height = 350,
    width = 350
)
(m|n).configure_axis(
    labelFontSize = 14,
    titleFontSize = 14,
    grid = False
).configure_title(
    fontSize = 16
)

alt.HConcatChart(...)

In [53]:
countAisles = pd.crosstab(data.aisle, data.eval_set)
countAisles['total'] = countAisles.prior + countAisles.train
count = countAisles.sort_values(by='total', ascending=False).head(15)
count['i'] = count.index
count.head()

eval_set,prior,train,total,i
aisle,,,,
fresh fruits,3642188,150473,3792661,fresh fruits
fresh vegetables,3418021,150609,3568630,fresh vegetables
packaged vegetables fruits,1765313,78493,1843806,packaged vegetables fruits
yogurt,1452343,55240,1507583,yogurt
packaged cheese,979763,41699,1021462,packaged cheese

In [54]:
m = alt.Chart(count, title="Count of Order of prior 15 Most Ordered from Aisles").mark_bar(size = 10).encode(
    alt.X('i', title = 'Product Name'),
    alt.Y('prior', title = 'Count of Orders')
).properties(
    height = 350,
    width = 350
)
n = alt.Chart(count, title="Count of Order of train 15 Most Ordered from Aisles").mark_bar(size = 10).encode(
    alt.X('i', title = 'Product Name'),
    alt.Y('train', title = 'Count of Orders')
).properties(
    height = 350,
    width = 350
)
(m|n).configure_axis(
    labelFontSize = 14,
    titleFontSize = 14,
    grid = False
).configure_title(
    fontSize = 15
)

alt.HConcatChart(...)

In [55]:
# Ratio of Departments
countDepartment = pd.crosstab(data.department, data.eval_set)
countDepartment['total'] = countDepartment.prior + countDepartment.train
countDepartment['%'] = countDepartment.total / countDepartment.total.sum()
count = countDepartment.sort_values(by='total', ascending=False)
count['i'] = count.index
count.head()

eval_set      prior   train    total         %           i
department
produce     9479291  409087  9888378  0.292390     produce
dairy eggs  5414016  217051  5631067  0.166505  dairy eggs
snacks      2887550  118862  3006412  0.088897      snacks
beverages   2690129  114046  2804175  0.082917   beverages
frozen      2236432  100426  2336858  0.069099      frozen

In [56]:
p = alt.Chart(count, title='Proportion of Items Sold from Each Department').mark_point().encode(
    x=alt.X('i', title='Department Name'),
    y=alt.Y('%', title='Total Percentage')
)
t = p.mark_text(
    align='left',
    baseline='middle',
    dy=7,
    fontSize = 12
).encode(
    text='i'
)
(p+t).configure_axis(
    labelFontSize = 14,
    titleFontSize = 14,
    grid = False
).configure_title(
    fontSize = 15
).properties(
    height = 600,
    width = 600
)

alt.LayerChart(...)

In [57]:
# Reorder ratio by departement

In [58]:
count = pd.DataFrame(data.groupby('department')['reordered'].mean())
count['i'] = count.index
count.head()

            reordered          i
department
alcohol      0.571221    alcohol
babies       0.577680     babies
bakery       0.628381     bakery
beverages    0.653651  beverages
breakfast    0.561351  breakfast

In [59]:
alt.Chart(count).mark_bar(size = 25).encode(
    alt.X('i', title = 'Department'),
    alt.Y('reordered', title = 'Ratio')
).configure_axis(
    labelFontSize = 16,
    titleFontSize = 16,
    grid = False
).configure_title(
    fontSize = 24
).properties(
    height = 350,
    width = 750
)

alt.Chart(...)

In [60]:
#Reorder ratio by the hour of the day or the day of the week?

In [61]:
count = data.groupby(['order_dow'])['reordered'].aggregate('mean').reset_index()
count

   order_dow  reordered
0          0   0.586483
1          1   0.603672
2          2   0.589720
3          3   0.586289
4          4   0.591123
5          5   0.595902
6          6   0.575244

In [62]:
alt.Chart(count, title='Reorder proportion on Each day of Week').mark_bar(size = 25).encode(
    alt.X('order_dow', title = 'Day of week'),
    alt.Y('reordered', title = 'Reorder Proportion')
).configure_axis(
    labelFontSize = 16,
    titleFontSize = 16,
    grid = False
).configure_title(
    fontSize = 24
).properties(
    height = 350,
    width = 300
).configure_bar(
    color = '#9CABFF'
)

alt.Chart(...)

In [63]:
count = data.groupby(['order_hour_of_day'])['reordered'].aggregate('mean').reset_index()
count.head()

   order_hour_of_day  reordered
0                  0   0.565726
1                  1   0.558149
2                  2   0.555574
3                  3   0.560501
4                  4   0.572370

In [64]:
alt.Chart(count, title='Reorder proportion on Each Hour of day').mark_bar(size = 20).encode(
    alt.X('order_hour_of_day', title = 'Order of day'),
    alt.Y('reordered', title = 'Reorder Proportion')
).configure_axis(
    labelFontSize = 16,
    titleFontSize = 16,
    grid = False
).configure_title(
    fontSize = 24
).properties(
    height = 350,
    width = 650
).configure_bar(
    color = '#E2A4FF'
)

alt.Chart(...)

In [65]:
reorderHourDow = data.groupby(['order_dow', 'order_hour_of_day'])['reordered'].aggregate('mean').reset_index()
reorderHourDow

     order_dow  order_hour_of_day  reordered
0            0                  0   0.576550
1            0                  1   0.553474
2            0                  2   0.554843
3            0                  3   0.568533
4            0                  4   0.548804
..         ...                ...        ...
163          6                 19   0.564884
164          6                 20   0.576726
165          6                 21   0.588330
166          6                 22   0.587386
167          6                 23   0.581613

[168 rows x 3 columns]

In [66]:
alt.Chart(reorderHourDow, title='Reorder Proportion by Day of Week vs Hour of Day').mark_rect().encode(
    x = alt.X('order_hour_of_day:O', title='Hour of the Day'),
    y = alt.Y('order_dow:O', title='Day of Week'),
    color=alt.Color('reordered:Q',scale=alt.Scale(scheme='greenblue'))
).configure_axis(
    labelFontSize=16,
    titleFontSize=16
).configure_title(
    fontSize = 24
).properties(
    height = 450,
    width = 450
)

alt.Chart(...)


It looks as though mornings, especially Sunday mornings, are prime time for reorders. On the other hand, late-night mid-week reorders are the least likely.